# Основные настройки
title: Агентство событий Екатерины Вержинской
description: "Доверьтесь профессионалам и получайте удовольствие от организации Вашего мероприятия!"
baseurl: "/main-site" # the subpath of your site, e.g. /blog
url: "http://verzhinskaya.ru" # the name of your domain

# Социальные сети
vkontakte: http://vk.com/e.verzhinskaya
facebook: https://www.facebook.com/e.verzhinskaya
twitter: 
instagram: https://www.instagram.com/e.verzhinskaya/
#youtube: http://youtube.com
#skype: skype:verzhinskaya
feed: no

# Копирайт
copyright: © 2016 Агентство событий Екатерины Вержинской




# Остальные настройки
# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics:
google_verification:

sass:
    sass_dir: _scss
    style: compressed
