######################
# Основные настройки #
######################
title: Агентство событий Екатерины Вержинской
description: "Доверьтесь профессионалам и получайте удовольствие от организации Вашего мероприятия!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://verzhinskaya.ru" # the name of your domain

# Настройки раздела "О нас"
about-video: "http://vk.com/video_ext.php?oid=154563095&id=171435400&hash=0ad09e597ca12266&hd=2"
about-text: <p class="about-text-1">В Вашей жизни бывает такое, что Вы хотите организовать яркое событие, но не знаете, как это сделать и с чего начать?</p><p class="about-text-2">У нас тоже такое было много лет назад. Шли годы — мы росли, развивались, набирались опыта в организации мероприятий разного масштаба и уровня.</p><p class="about-text-3">На данный момент мы являемся командой профессионалов, готовых помочь Вам сделать любое предстоящее событие ярким, интересным и запоминающимся.</p>

# Настройки раздела "Три колонки" ("Более...")
three-col1-img: "wise.png"
three-col1-txt: "Более <strong>10</strong>&nbsp;лет<br>опыта работы"
three-col2-img: "like.png"
three-col2-txt: "Более <strong>100</strong><br>мероприятий в&nbsp;год"
three-col3-img: "heart-smiley.png"
three-col3-txt: "Более <strong>1000<strong><br>благодарных<br>клиентов"

# Настройки телефонов
phone1: "<strong>+7 (978) 215-71-05</strong> (Крым)"
phone2: "<strong>+7 (967) 741-00-51</strong> (Уфа)"

# Социальные сети
vkontakte: http://vk.com/e.verzhinskaya
facebook: https://www.facebook.com/e.verzhinskaya
twitter: 
instagram: https://www.instagram.com/e.verzhinskaya/
#youtube: http://youtube.com
#skype: skype:verzhinskaya
feed: no

# Копирайт
copyright: © 2016 Агентство событий Екатерины Вержинской



#######################
# Остальные настройки #
#######################
# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics:
google_verification:

sass:
    sass_dir: _scss
    style: compressed
